[tool.poetry]
name = "django-todo-webapp"
version = "0.1.0"
description = ""
authors = ["amitmodi06 <amitmodi06@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
