# Generated by Django 4.2.7 on 2023-12-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_task',
            name='id_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo_task',
            name='task',
            field=models.CharField(help_text='Enter a to do task', max_length=100),
        ),
    ]
