# Generated by Django 4.2.7 on 2023-12-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0002_todo_task_id_done_alter_todo_task_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_task',
            old_name='id_done',
            new_name='is_done',
        ),
    ]
