# Generated by Django 4.2.7 on 2023-12-03 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0003_rename_id_done_todo_task_is_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo_task',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='todo_task',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
